config/routes.rb
Syukeikun::Application.routes.draw do
  resources :screenings do
    resources :movies do 
   	  resources :reviews
   	end
  end

  resources :users

  resources :sessions

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'

  root :to => 'screenings#index'
end

app/models/screening.rb
class Screening < ActiveRecord::Base
  attr_accessible :nth, :subtitle, :description

  has_many :movies
end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  # GET /screenings
  # GET /screenings.json
  def index
    @screenings = Screening.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @screenings }
    end
  end

  # GET /screenings/1
  # GET /screenings/1.json
  def show
    @screening = Screening.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @screening }
    end
  end

  # GET /screenings/new
  # GET /screenings/new.json
  def new
    @screening = Screening.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @screening }
    end
  end

  # GET /screenings/1/edit
  def edit
    @screening = Screening.find(params[:id])
  end

  # POST /screenings
  # POST /screenings.json
  def create
    @screening = Screening.new(params[:screening])

    respond_to do |format|
      if @screening.save
        format.html { redirect_to @screening, notice: 'Screening was successfully created.' }
        format.json { render json: @screening, status: :created, location: @screening }
      else
        format.html { render action: "new" }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /screenings/1
  # PUT /screenings/1.json
  def update
    @screening = Screening.find(params[:id])

    respond_to do |format|
      if @screening.update_attributes(params[:screening])
        format.html { redirect_to @screening, notice: 'Screening was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenings/1
  # DELETE /screenings/1.json
  def destroy
    @screening = Screening.find(params[:id])
    @screening.destroy

    respond_to do |format|
      format.html { redirect_to screenings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/views/screenings/_form.html.erb
<%= form_for(@screening) do |f| %>
  <% if @screening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screening.errors.count, "error") %> prohibited this screening from being saved:</h2>

      <ul>
      <% @screening.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nth %><br />
    <%= f.number_field :nth %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screenings/edit.html.erb
<h1>Editing screening</h1>

<%= render 'form' %>

<%= link_to 'Show', @screening %> |
<%= link_to 'Back', screenings_path %>

app/views/screenings/index.html.haml
%h1 東京理科大学映画研究部

%h2 上映会一覧

.row
  - @screenings.each do |screening|
    .span4
      %h2= link_to screening.subtitle, screening_movies_path(screening)
      %p #{screening.description} 
      - if current_user && current_user.admin?
        %td= link_to 'Edit', edit_screening_path(screening)
        %td= link_to 'Destroy', screening, method: :delete, data: { confirm: 'Are you sure?' }

- if current_user && current_user.admin? 
  = link_to 'New Screening', new_screening_path 

app/views/screenings/new.html.erb
<h1>New screening</h1>

<%= render 'form' %>

<%= link_to 'Back', screenings_path %>

app/views/screenings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nth:</b>
  <%= @screening.nth %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @screening.subtitle %>
</p>


<%= link_to 'Edit', edit_screening_path(@screening) %> |
<%= link_to 'Back', screenings_path %>